import { useEffect, useState } from 'react';
import { ArrowUpRight, BookOpen, Compass, Heart, Map, Menu, Plus, User, X } from 'lucide-react';
import type { Bootstrap, Member } from '../shared/types';
import { request } from './api';
import { Discover } from './Discover';
import { PlacePage } from './PlacePage';
import { Account } from './Account';
import { Admin, Moderation } from './Management';
import { PlaceForm } from './forms';
import { Notice } from './components';

export function App({initial,path='/',search=''}:{initial:Bootstrap;path?:string;search?:string}){
  const [member,setMember]=useState<Member|null>(null);const [menu,setMenu]=useState(false);const [offline,setOffline]=useState(false);const [install,setInstall]=useState<any>(null);const [installHelp,setInstallHelp]=useState(false);
  const refresh=async()=>setMember(await request<Member|null>('/api/me'));
  useEffect(()=>{void refresh().catch(()=>{});setOffline(!navigator.onLine);const online=()=>setOffline(!navigator.onLine);const prompt=(e:Event)=>{e.preventDefault();setInstall(e);};window.addEventListener('online',online);window.addEventListener('offline',online);window.addEventListener('beforeinstallprompt',prompt);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',online);window.removeEventListener('beforeinstallprompt',prompt);};},[]);
  const links=[['/','Discover'],['/map','Map'],['/links','Useful links'],['/about','Our community']];
  return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><a href="/" className="brand" aria-label="glutenfree.mt home"><img className="brand-icon" src="/icon.svg" width="43" height="43" alt=""/><span>glutenfree.mt<span className="brand-locality">MALTA &amp; GOZO</span></span></a><nav className={menu?'main-nav open':'main-nav'} aria-label="Main navigation">{links.map(([href,label])=><a key={href} href={href} className={path===href?'active':''}>{label}</a>)}</nav><div className="header-actions"><a href="/suggest" className="button small-button"><Plus size={15}/> Add a place</a><a className="account-button" href="/account"><User size={17}/><span>{member?member.name.split(' ')[0]:'Sign in'}</span></a><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></div></header>
    {offline&&<Notice>You’re offline. Connect to see current reviews and verification details.</Notice>}
    <main id="main">{path==='/'||path==='/map'?<Discover data={initial} path={path} search={search}/>:path.startsWith('/places/')?initial.detail?<PlacePage detail={initial.detail} member={member} adverts={initial.adverts}/>:<NotFound/>:path==='/account'?<Account member={member} data={initial} refresh={refresh}/>:path==='/suggest'?<div className="page narrow"><p className="eyebrow">PASS ON A GOOD FIND</p><h1>Make room for<br/><em>another place.</em></h1><PlaceForm member={member}/></div>:path==='/moderation'?<Moderation member={member} data={initial}/>:path==='/admin'?<Admin member={member}/>:path==='/links'?<div className="page"><p className="eyebrow">A LITTLE HELP ALONG THE WAY</p><h1>Useful links.</h1><p className="lead">Local support, trusted organisations, and a few useful starting points.</p>{[...new Set(initial.links.map(l=>l.category))].map(category=><section className="detail-section" key={category}><h2>{category}</h2><div className="resource-grid">{initial.links.filter(l=>l.category===category).map(l=><a className="resource-card" key={l.id} href={l.url} target="_blank" rel="noreferrer"><BookOpen size={24}/><h3>{l.title}</h3><p>{l.description}</p><span className="text-link">Visit website <ArrowUpRight size={16}/></span></a>)}</div></section>)}</div>:path==='/about'?<About/>:path==='/privacy'?<Privacy/>:<NotFound/>}</main>
    <footer className="site-footer"><div className="footer-main"><div><a href="/" className="footer-brand">glutenfree.mt<span>✳</span></a><p>Local knowledge. A shared table.<br/>Made for the coeliac community in Malta & Gozo.</p></div><div><p className="eyebrow">EXPLORE</p><a href="/">Find a place</a><a href="/links">Useful links</a><a href="/suggest">Suggest a place</a></div><div><p className="eyebrow">OUR COMMUNITY</p><a href="/about">About this project</a><a href="/privacy">Privacy & guidelines</a><button className="footer-install" onClick={async()=>{if(install){await install.prompt();setInstall(null);}else setInstallHelp(!installHelp);}}>Install on your phone ↗</button>{installHelp&&<p className="small">On iPhone, open your browser’s Share menu and choose Add to Home Screen. On Android, look for Install app in your browser menu.</p>}</div></div><div className="footer-bottom"><p>Independent and community-run. Not affiliated with CAM. Always confirm your requirements with the restaurant.</p><span>Shared with care <Heart size={13}/></span></div></footer>
    <nav className="bottom-nav" aria-label="Mobile navigation">{([['/','Discover',Compass],['/map','Map',Map],['/links','Useful links',BookOpen],['/account','Account',User]] as const).map(([href,label,Icon])=><a href={href} key={href} className={path===href?'active':''}><Icon size={20}/><span>{label}</span></a>)}</nav>
  </>;
}
function NotFound(){return <div className="page empty-state"><h1>We couldn’t find that page.</h1><p>There’s still a whole island of places to explore.</p><a className="button primary" href="/">Back to the directory</a></div>;}
function About(){return <article className="page prose"><p className="eyebrow">LOCAL KNOWLEDGE, SHARED</p><h1>A place at<br/><em>the table.</em></h1><p className="lead">glutenfree.mt is an independent community project helping people find places that cater for coeliacs in Malta and Gozo.</p><h2>Built from community experience</h2><p>This directory began as a shared list of places and feedback. We keep the original comments labelled as imported community feedback, without inventing dates or ratings. New community reviews, photos, and owner replies are checked by moderators before they appear. Admin contributions publish immediately.</p><h2 id="verification">What “Verified by CAM” means here</h2><p>Site admins manually record whether a place has CAM verification. The badge is separate from community ratings and verified restaurant ownership. This website is not run by or affiliated with CAM. Check the displayed verification date and confirm your requirements directly with the business.</p><h2>Honest experiences, useful details</h2><p>A star rating describes a member’s overall visit. It is not a safety certification. Details about menus and preparation come from community contributions and can change. Both positive and negative experiences are welcome.</p><h2>Owners are part of the conversation</h2><p>Admins manually verify restaurant representatives. Owners can reply to feedback on their linked places; replies are labelled and moderated. They cannot change other people’s reviews or verify their own business.</p><h2>Keeping it going</h2><p>Occasional clearly labelled adverts may help cover running costs. Sponsorship does not change rankings, ratings, or verification.</p><a className="button primary" href="/suggest">Share a place <ArrowUpRight size={16}/></a></article>;}
function Privacy(){return <article className="page prose"><p className="eyebrow">COMMUNITY GUIDELINES</p><h1>Share with care.</h1><h2>What we ask of contributors</h2><p>Describe your own experience honestly. Be specific and respectful, avoid personal attacks, and upload only photos you have permission to share. Do not include anyone’s private contact details or health information in public feedback. Owners must not review their own businesses.</p><h2>Before your contribution appears</h2><p>Community reviews, photos, new places, corrections, and owner replies need moderator approval. Admin contributions publish immediately. Edits are checked again; the previous approved version stays visible while an edit is pending. You can report published content for review.</p><h2>Your account and contributions</h2><p>We store your email, display name, sign-in information, and contributions to operate your account and moderate the directory. Your display name is public beside approved feedback; your email and ownership-check details are private. Admins can access account information to manage the community.</p><h2>Photos and location</h2><p>Photos are resized and re-encoded to remove metadata before storage. Your device location is requested only when you select Near me and is used in your browser for approximate distances. It is not saved to your profile.</p><h2>Cookies and external services</h2><p>Sign-in uses essential session cookies. Google sign-in, external map providers, restaurant links, and sponsor links involve the respective providers. We do not include advertising trackers or analytics scripts.</p><h2>Removing your data</h2><p>Use Account to withdraw pending submissions, remove reviews from public view, or delete your account. Account deletion removes your login and public personal contributions; rejected photos are cleaned up by a daily job. Minimal moderation records may remain without your account identity.</p><p className="notice">Before public launch, the community operator must add their contact details and final retention policy here.</p></article>;}
