import { Fragment, lazy, Suspense, useMemo, useState } from 'react';
import { ArrowDown, ArrowUpRight, Compass, List, Map as MapIcon, Navigation, Search, SlidersHorizontal, X } from 'lucide-react';
import type { Bootstrap } from '../shared/types';
import { CUISINES, distanceKm, filterPlaces, businessTypes, PLACE_TYPES, SERVICES } from '../shared/domain';
import { Notice, PlaceCard, Sponsor } from './components';
const MapView=lazy(()=>import('./MapView'));

export function Discover({data,path,search}:{data:Bootstrap;path:string;search:string}){
  const params=new URLSearchParams(search);
  const [filters,setFilters]=useState({q:params.get('q')||'',island:params.get('island')||'',locality:params.get('locality')||'',cuisine:params.get('cuisine')||'',type:params.get('type')||'',service:params.get('service')||'',price:params.get('price')||'',item:params.get('category')==='shops'?'':params.get('item')||''});
  const [advanced,setAdvanced]=useState(false);const [sort,setSort]=useState('name');const [position,setPosition]=useState<{lat:number;lng:number}|null>(null);const [geoError,setGeoError]=useState('');const [locating,setLocating]=useState(false);const [limit,setLimit]=useState(12);
  const view=path==='/map'?'map':'list';
  const category=params.get('category')==='shops'?'shop':path==='/shops'?'shop':path==='/restaurants'||path==='/'?'restaurant':undefined;
  const route=category==='shop'?'/shops':category==='restaurant'&&path==='/'?'/restaurants':path;
  const catalog=(data.business_types||PLACE_TYPES.map((key,index)=>({key,label:key,category: ['Butcher','Food shop','Food producer','Importer/distributor'].includes(key)?'shop' as const:'restaurant' as const,sort_order:index,active:1}))).filter(t=>!category||t.category===category);
  const categoryKeys=new Set(catalog.map(t=>t.key));
  const categoryPlaces=category?data.places.filter(p=>businessTypes(p).some(t=>categoryKeys.has(t))):data.places;
  const localities=[...new Set(data.places.filter(p=>!filters.island||p.island===filters.island).map(p=>p.locality).filter(Boolean))].sort();
  function update(patch:Partial<typeof filters>){const next={...filters,...patch};setFilters(next);setLimit(12);const qs=new URLSearchParams();for(const [k,v]of Object.entries(next))if(v)qs.set(k,String(v));history.replaceState(null,'',`${route}${qs.size?'?'+qs:''}`);}
  const filtered=useMemo(()=>filterPlaces(categoryPlaces,filters,data.gluten_free_item_catalog).sort((a,b)=>{
    if(sort==='rating')return (b.rating??-1)-(a.rating??-1)||b.review_count-a.review_count;
    if(sort==='nearby'&&position){const d=(p:typeof a)=>p.premises!=='none'&&p.coordinates_checked&&p.latitude!==null&&p.longitude!==null?distanceKm(position,{lat:p.latitude,lng:p.longitude}):Infinity;return d(a)-d(b);}
    return a.name.localeCompare(b.name);
  }),[categoryPlaces,filters,sort,position,data.gluten_free_item_catalog]);
  const qs=new URLSearchParams();for(const [k,v]of Object.entries(filters))if(v)qs.set(k,String(v));
  function nearMe(){setGeoError('');if(!navigator.geolocation){setGeoError('Location is unavailable in this browser. Choose a locality instead.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude});setSort('nearby');setLocating(false);if(!data.places.some(p=>p.coordinates_checked))setGeoError('Your location is ready. Business map pins still need checking; browse by locality for now.');},()=>{setLocating(false);setGeoError('Location was unavailable or not allowed. You can still search by locality.');},{timeout:10000,maximumAge:60000});}
  const heading=category==='shop'?'Gluten-free shops and suppliers in Malta & Gozo':category==='restaurant'?'Gluten-free restaurants and places to eat in Malta & Gozo':'Gluten-free places in Malta & Gozo';
  return <>
    <section id="discover" className="discover"><header className="directory-intro"><h1>{heading}</h1><p>Find safe places for celiacs to eat, shop, and order gluten free food, with experiences shared by the coeliac community.</p></header>
      <div className="search-bar"><label className="search-input"><Search size={20}/><span className="sr-only">Search places</span><input placeholder="A place, locality or gluten-free food…" value={filters.q} onChange={e=>update({q:e.target.value})}/>{filters.q&&<button aria-label="Clear search" onClick={()=>update({q:''})}><X size={16}/></button>}</label><button className="near-button" onClick={nearMe} disabled={locating}><Navigation size={17}/>{locating?'Locating…':'Near me'}</button></div>
      <div className="filter-row"><div className="island-tabs" aria-label="Filter by island">{['','Malta','Gozo'].map(i=><button key={i} className={filters.island===i?'active':''} onClick={()=>update({island:i,locality:''})}>{i||'Both islands'}</button>)}</div><label className="filter-select"><span className="sr-only">Locality</span><select value={filters.locality} onChange={e=>update({locality:e.target.value})}><option value="">All localities</option>{localities.map(l=><option key={l}>{l}</option>)}</select></label><button className={`filter-button ${advanced?'active':''}`} onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><SlidersHorizontal size={16}/> More filters</button></div>
      {advanced&&<div className="advanced-filters">{([['cuisine','Cuisine',CUISINES],['type','Business type',catalog.map(t=>t.key)],['service','Service',SERVICES],['price','Price band',['1','2','3','4']]] as const).map(([key,label,options])=><label key={key}>{label}<select value={filters[key]} onChange={e=>update({[key]:e.target.value})}><option value="">Any {label.toLowerCase()}</option>{options.map(o=><option key={o} value={o}>{key==='price'?'€'.repeat(Number(o)):data.business_types?.find(t=>t.key===o)?.label||o}</option>)}</select></label>)}{category!=='shop'&&<label>Gluten-free item<select value={filters.item} onChange={e=>update({item:e.target.value})}><option value="">Any gluten-free item</option>{data.gluten_free_item_catalog?.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label>}<button className="text-link" onClick={()=>update({q:'',island:'',locality:'',cuisine:'',type:'',service:'',price:'',item:''})}>Clear all filters</button><p className="small muted">Price bands: € under €15 · €€ €15–24 · €€€ €25–39 · €€€€ €40+. Main meal, excluding drinks; estimates may vary.</p></div>}
      {geoError&&<Notice>{geoError}</Notice>}
      <div className="results-toolbar"><div className="results-summary"><p><strong>{filtered.length}</strong> {filtered.length===1?'place':'places'} to explore</p><a className="text-link" href="/suggest">Add a business <ArrowUpRight size={16}/></a></div><div className="results-controls"><label><span className="sr-only">Sort places</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name, A–Z</option><option value="rating">Highest rated</option>{position&&<option value="nearby">Nearest first</option>}</select></label><div className="view-toggle"><a className={view==='list'?'active':''} href={`${category==='shop'?'/shops':'/restaurants'}${qs.size?'?'+qs:''}`}><List size={16}/>List</a><a className={view==='map'?'active':''} href={`/map${qs.size?'?'+qs:''}`}><MapIcon size={16}/>Map</a></div></div></div>
      {view==='map'?<Suspense fallback={<p>Loading map…</p>}><MapView places={filtered} styleUrl={data.config.mapStyle}/></Suspense>:filtered.length?<><div className="place-grid">{filtered.slice(0,limit).map((p,i)=><Fragment key={p.id}><PlaceCard place={p} distance={sort==='nearby'&&position&&p.premises!=='none'&&p.coordinates_checked&&p.latitude!==null&&p.longitude!==null?distanceKm(position,{lat:p.latitude,lng:p.longitude}):undefined}/>{(i===7||i===15)&&<Sponsor ad={data.adverts.filter(a=>a.placement==='list')[i===7?0:1]}/>}</Fragment>)}</div>{filtered.length>limit&&<div className="load-more"><button className="button" onClick={()=>setLimit(limit+12)}>Explore more places <ArrowDown size={16}/></button><p className="small muted">Showing {Math.min(limit,filtered.length)} of {filtered.length}</p></div>}</>:<div className="empty-state"><Compass size={36}/><h3>No places found this time</h3><p>Try another locality or loosen your filters. Know a place we’re missing?</p><a className="button" href="/suggest">Suggest a place</a></div>}
    </section>
    <section className="contribute-banner"><div><p className="eyebrow">PULL UP A CHAIR</p><h2>Your experience could make<br/>someone else’s day.</h2><p>A favourite café. A helpful chef. A detail worth sharing.</p></div><a className="button primary" href="/suggest">Share a place <ArrowUpRight size={18}/></a></section>
  </>;
}
