import { useState, type FormEvent } from 'react';
import { Star, Upload } from 'lucide-react';
import type { Member, Place, Photo } from '../shared/types';
import { CUISINES, PLACE_TYPES } from '../shared/domain';
import { request, preparePhoto } from './api';
import { FormStatus, Notice, SubmitButton, useAction } from './components';

export function SignInPrompt(){return <Notice><a href="/account">Sign in</a> to share your experience. Browsing is always open to everyone.</Notice>;}
export function ReviewForm({place,initial,onDone,admin=false}:{admin?:boolean;place:Place;initial?:{body:string;rating:number;visit_date:string};onDone?:()=>void}){
  const action=useAction();const [rating,setRating]=useState(initial?.rating||0);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await action.run(async()=>{await request('/api/submissions',{kind:'review',place_id:place.id,payload:{body:form.get('body'),rating,visit_date:form.get('visit_date')}});onDone?.();},admin?'Your review is published. Thank you for sharing.':'Your review is awaiting approval. Thank you for sharing.');}
  return <form onSubmit={submit} className="stack-form"><p className="muted">Share your experience at {place.name}. {admin?'Your review will be published immediately.':'Reviews are checked by a community moderator before appearing.'}</p><fieldset className="rating-input"><legend>Overall experience</legend>{[1,2,3,4,5].map(n=><label key={n}><input required type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)}/><Star size={32} fill={n<=rating?'currentColor':'none'}/><span className="sr-only">{n} {n===1?'star':'stars'}</span></label>)}</fieldset><label>When did you visit?<input name="visit_date" type="date" required max={new Date().toISOString().slice(0,10)} defaultValue={initial?.visit_date}/></label><label>Your experience<textarea name="body" required minLength={3} maxLength={3000} rows={5} defaultValue={initial?.body} placeholder="What did you eat? How did the team handle your gluten-free requirements?"/></label><FormStatus {...action}/><SubmitButton busy={action.busy}>{admin?'Publish review':'Send for approval'}</SubmitButton></form>;
}
export function MessageForm({kind,placeId,targetId,targetType,onDone,admin=false}:{admin?:boolean;kind:'reply'|'report'|'owner_claim';placeId:string;targetId?:string;targetType?:string;onDone?:()=>void}){
  const a=useAction();return <form className="stack-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{await request('/api/submissions',{kind,place_id:placeId,target_id:targetId,payload:{body:f.get('body'),...(targetType?{target_type:targetType}:{})}});onDone?.();},admin&&kind!=='owner_claim'?'Your changes have been applied.':'Sent. Your submission is awaiting approval.');}}><p className="muted">{kind==='owner_claim'?'Tell the admins your role at this business and how they can independently confirm it. These details stay private.':kind==='report'?admin?'Submitting this report will hide the content immediately.':'Explain what needs attention. A moderator will review the content.':admin?'Your owner reply will be published immediately.':'Your response will appear as an owner reply once a moderator approves it.'}</p><label>{kind==='reply'?'Your reply':'Details'}<textarea name="body" rows={5} required minLength={3} maxLength={kind==='reply'?3000:1000}/></label><FormStatus {...a}/><SubmitButton busy={a.busy}>{admin?'Save changes':'Send for approval'}</SubmitButton></form>;
}
export function PhotoForm({placeId,admin=false}:{placeId:string;admin?:boolean}){
  const a=useAction();return <form className="stack-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{const files=f.getAll('photos').filter(v=>v instanceof File&&v.size) as File[];if(!files.length||files.length>5)throw new Error('Choose between one and five photos.');let uploaded=0;for(const file of files){try{const blob=await preparePhoto(file);const body=new FormData();body.set('photo',blob,'photo.jpg');body.set('place_id',placeId);body.set('caption',String(f.get('caption')||''));const r=await fetch('/api/photos',{method:'POST',body});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Photo upload failed');uploaded++;}catch(e){throw new Error(`${uploaded} photo(s) submitted. ${e instanceof Error?e.message:'Please retry the remaining photos.'}`);}}},admin?'Your photos are published.':'Your photos are awaiting approval.');}}><p className="muted">Share your own photos of food, menus, or the place. We resize them and remove location metadata.</p><label className="upload-field"><Upload/> Choose up to 5 photos<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple required/></label><label>Caption<input name="caption" required minLength={3} maxLength={200} placeholder="Tell us what is in the photo"/></label><FormStatus {...a}/><SubmitButton busy={a.busy}>{admin?'Save changes':'Send for approval'}</SubmitButton></form>;
}
export { PlaceForm } from './PlaceForm';

export function CoverForm({placeId,photos,currentPhoto,admin=false}:{admin?:boolean;placeId:string;photos:Photo[];currentPhoto?:string}){
  const a=useAction();
  return <details className="cover-choice"><summary>Choose your place’s cover photo</summary><p>Choose an approved photo for the banner and directory card. {admin?'Your cover choice takes effect immediately.':'Your current cover stays visible until a moderator approves the change.'}</p>{photos.length?<form className="stack-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{await request('/api/submissions',{kind:'correction',place_id:placeId,payload:{cover_photo_id:f.get('cover')}});},admin?'Your cover photo has been updated.':'Your cover choice is awaiting moderator approval.');}}><label>Cover photo<select name="cover" defaultValue={currentPhoto} required>{photos.map((photo,i)=><option key={photo.id} value={photo.id}>{i+1}. {photo.caption}</option>)}</select></label><FormStatus {...a}/><SubmitButton busy={a.busy}>{admin?'Save cover photo':'Submit cover choice'}</SubmitButton></form>:<p>{admin?'Use Add photos first, then choose a cover here.':'Use Add photos first. Once a photo is approved, you can choose it here.'}</p>}</details>;
}
