import { useState, type FormEvent } from 'react';
import { Star, Upload } from 'lucide-react';
import type { Member, Place } from '../shared/types';
import { CUISINES, PLACE_TYPES } from '../shared/domain';
import { request, preparePhoto } from './api';
import { FormStatus, Notice, SubmitButton, useAction } from './components';

export function SignInPrompt(){return <Notice><a href="/account">Sign in</a> to share your experience. Browsing is always open to everyone.</Notice>;}
export function ReviewForm({place,initial,onDone}:{place:Place;initial?:{body:string;rating:number;visit_date:string};onDone?:()=>void}){
  const action=useAction();const [rating,setRating]=useState(initial?.rating||0);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await action.run(async()=>{await request('/api/submissions',{kind:'review',place_id:place.id,payload:{body:form.get('body'),rating,visit_date:form.get('visit_date')}});onDone?.();},'Your review is awaiting approval. Thank you for sharing.');}
  return <form onSubmit={submit} className="stack-form"><p className="muted">Share your experience at {place.name}. Reviews are checked by a community moderator before appearing.</p><fieldset className="rating-input"><legend>Overall experience</legend>{[1,2,3,4,5].map(n=><label key={n}><input required type="radio" name="rating" value={n} checked={rating===n} onChange={()=>setRating(n)}/><Star size={32} fill={n<=rating?'currentColor':'none'}/><span className="sr-only">{n} {n===1?'star':'stars'}</span></label>)}</fieldset><label>When did you visit?<input name="visit_date" type="date" required max={new Date().toISOString().slice(0,10)} defaultValue={initial?.visit_date}/></label><label>Your experience<textarea name="body" required minLength={3} maxLength={3000} rows={5} defaultValue={initial?.body} placeholder="What did you eat? How did the team handle your gluten-free requirements?"/></label><FormStatus {...action}/><SubmitButton busy={action.busy}/></form>;
}
export function MessageForm({kind,placeId,targetId,targetType,onDone}:{kind:'reply'|'report'|'owner_claim';placeId:string;targetId?:string;targetType?:string;onDone?:()=>void}){
  const a=useAction();return <form className="stack-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{await request('/api/submissions',{kind,place_id:placeId,target_id:targetId,payload:{body:f.get('body'),...(targetType?{target_type:targetType}:{})}});onDone?.();},'Sent. Your submission is awaiting approval.');}}><p className="muted">{kind==='owner_claim'?'Tell the admins your role at this business and how they can independently confirm it. These details stay private.':kind==='report'?'Explain what needs attention. A moderator will review the content.':'Your response will appear as an owner reply once a moderator approves it.'}</p><label>{kind==='reply'?'Your reply':'Details'}<textarea name="body" rows={5} required minLength={3} maxLength={kind==='reply'?3000:1000}/></label><FormStatus {...a}/><SubmitButton busy={a.busy}/></form>;
}
export function PhotoForm({placeId}:{placeId:string}){
  const a=useAction();return <form className="stack-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void a.run(async()=>{const files=f.getAll('photos').filter(v=>v instanceof File&&v.size) as File[];if(!files.length||files.length>5)throw new Error('Choose between one and five photos.');let uploaded=0;for(const file of files){try{const blob=await preparePhoto(file);const body=new FormData();body.set('photo',blob,'photo.jpg');body.set('place_id',placeId);body.set('caption',String(f.get('caption')||''));const r=await fetch('/api/photos',{method:'POST',body});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Photo upload failed');uploaded++;}catch(e){throw new Error(`${uploaded} photo(s) submitted. ${e instanceof Error?e.message:'Please retry the remaining photos.'}`);}}},'Your photos are awaiting approval.');}}><p className="muted">Share your own photos of food, menus, or the place. We resize them and remove location metadata.</p><label className="upload-field"><Upload/> Choose up to 5 photos<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple required/></label><label>Caption<input name="caption" required minLength={3} maxLength={200} placeholder="Tell us what is in the photo"/></label><FormStatus {...a}/><SubmitButton busy={a.busy}/></form>;
}
export function PlaceForm({member,place,onDone}:{member:Member|null;place?:Place;onDone?:()=>void}){
  const a=useAction();const [cuisines,setCuisines]=useState<string[]>(place?.cuisines||[]);
  if(!member)return <SignInPrompt/>;
  return <form className="stack-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const str=(k:string)=>String(f.get(k)||'');const num=(k:string)=>str(k)===''?null:Number(str(k));void a.run(async()=>{await request('/api/submissions',{kind:place?'correction':'place',place_id:place?.id,payload:{name:str('name'),type:str('type'),locality:str('locality'),island:str('island'),address:str('address'),latitude:num('latitude'),longitude:num('longitude'),cuisines,price_min:num('price_min'),price_max:num('price_max'),price_basis:str('price_basis'),menu_info:str('menu_info'),website:str('website'),menu_url:str('menu_url'),social_url:str('social_url'),phone:str('phone'),business_status:str('business_status')}});onDone?.();},'Thank you. Your suggestion is awaiting approval.');}}>
    <p className="muted">{place?'Suggest updated details. A moderator will review the changes.':'Help someone find their next table. Add what you know; leave uncertain details blank.'}</p>
    <label>Place name<input name="name" required minLength={3} maxLength={120} defaultValue={place?.name}/></label><div className="form-grid"><label>Place type<select name="type" defaultValue={place?.type||'Restaurant'}>{PLACE_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Island<select name="island" defaultValue={place?.island||'Malta'}><option>Malta</option><option>Gozo</option></select></label><label>Locality<input name="locality" maxLength={80} defaultValue={place?.locality}/></label><label>Phone<input name="phone" maxLength={40} defaultValue={place?.phone}/></label></div><label>Street address<input name="address" maxLength={250} defaultValue={place?.address}/></label>
    <fieldset><legend>Cuisine <span className="muted">(up to 5)</span></legend><div className="tag-options">{CUISINES.map(c=><label key={c}><input type="checkbox" checked={cuisines.includes(c)} onChange={e=>setCuisines(e.target.checked?[...cuisines,c].slice(0,5):cuisines.filter(x=>x!==c))}/>{c}</label>)}</div></fieldset>
    <div className="form-grid"><label>Approx. minimum € per person<input name="price_min" type="number" min="0" max="1000" step="0.5" defaultValue={place?.price_min??''}/></label><label>Approx. maximum € per person<input name="price_max" type="number" min="0" max="1000" step="0.5" defaultValue={place?.price_max??''}/></label></div><label>What does this estimate cover?<input name="price_basis" required maxLength={160} defaultValue={place?.price_basis||'Main meal per person, excluding drinks'}/></label><label>Gluten-free menu information<textarea name="menu_info" rows={3} maxLength={500} defaultValue={place?.menu_info} placeholder="For example, a separate menu or marked allergens. Please describe only what you know."/></label>
    <div className="form-grid">{([['website','Website'],['menu_url','Menu link'],['social_url','Social page']] as const).map(([key,label])=><label key={key}>{label}<input name={key} type="url" pattern="https://.*" placeholder="https://" defaultValue={place?.[key]}/></label>)}<label>Business status<select name="business_status" defaultValue={place?.business_status||'open'}><option value="open">Open</option><option value="temporarily_closed">Temporarily closed</option><option value="closed">Permanently closed</option></select></label></div>
    <details><summary>Map coordinates (optional)</summary><p className="small muted">A moderator will check the pin before it appears on the map.</p><div className="form-grid"><label>Latitude<input name="latitude" type="number" step="any" min="35.7" max="36.2" defaultValue={place?.latitude??''}/></label><label>Longitude<input name="longitude" type="number" step="any" min="14.1" max="14.7" defaultValue={place?.longitude??''}/></label></div></details><FormStatus {...a}/><SubmitButton busy={a.busy}/>
  </form>;
}
