import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Camera, Flag, MapPin, MessageCircle, Pencil, Phone, ShieldCheck } from 'lucide-react';
import type { Advert, BusinessType, GlutenFreeItem, Detail, Member } from '../shared/types';
import { AuthorIdentity } from './Profiles';
import { MENU_OPTIONS } from '../shared/place-options';
import { priceBand, priceLabel, businessTypeLabel } from '../shared/domain';
import { CamBadge, Illustration, Modal, Notice, Rating, Sponsor } from './components';
import { CoverForm, MessageForm, PhotoForm, PlaceForm, ReviewForm, SignInPrompt } from './forms';

export function PlacePage({detail,member,adverts,businessTypes,glutenFreeItems}:{detail:Detail;member:Member|null;adverts:Advert[];businessTypes?:BusinessType[];glutenFreeItems?:GlutenFreeItem[]}){
  const [modal,setModal]=useState<{kind:string;id?:string;target?:string}|null>(null);const p=detail.place;const owner=member?.ownerships.includes(p.id);const cover=detail.photos.find(photo=>photo.id===p.photo)||detail.photos[0];
  const directions=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([p.name,p.address,p.locality,p.island].filter(Boolean).join(', '))}`;
  return <div className="detail-page"><a className="back-link" href="/" onClick={e=>{if(document.referrer&&new URL(document.referrer).origin===location.origin&&new URL(document.referrer).pathname==='/'){e.preventDefault();history.back();}}}><ArrowLeft size={16}/> Back to places</a><div className="detail-top"><div><p className="eyebrow">{businessTypeLabel(p)} · {p.island}</p><h1>{p.name}</h1>{p.branch_name&&<p className="branch-name">{p.branch_name}</p>}<p className="location"><MapPin size={16}/>{p.locality||'Locality to be confirmed'}</p><div className="detail-badges"><Rating rating={p.rating} count={p.review_count}/>{!!p.cam_verified&&<CamBadge/>}{p.cuisines.map(c=><span className="badge" key={c}>{c}</span>)}{p.business_status!=='open'&&<span className="badge warning">{p.business_status==='closed'?'Permanently closed':'Temporarily closed'}</span>}</div></div><button className="button primary" onClick={()=>setModal({kind:'review'})}><Pencil size={16}/> Write a review</button></div>
    {p.short_description&&<p className="place-short-description">{p.short_description}</p>}
    <section className="detail-section"><h2>Gluten-free items available</h2>{p.gluten_free_items?.length?<div className="tag-options">{p.gluten_free_items.map(key=><span className="badge" key={key}>{glutenFreeItems?.find(item=>item.key===key)?.label||key.replaceAll('_',' ')}</span>)}</div>:<p className="muted">Items not yet recorded.</p>}</section>
    <div className="detail-photo">{cover?<img src={`/photos/${cover.id}`} alt={cover.caption}/>:<Illustration type={p.type} large/>}<button className="button photo-button" onClick={()=>setModal({kind:'photo'})}><Camera size={16}/> Add photos</button></div>
    {owner&&<CoverForm admin={member?.role==='admin'} placeId={p.id} photos={detail.photos} currentPhoto={cover?.id}/>}
    {detail.photos.length>1&&<div className="photo-gallery">{detail.photos.map(ph=><figure key={ph.id}><a href={`/photos/${ph.id}`} target="_blank" rel="noreferrer"><img src={`/photos/${ph.id}?size=thumb`} alt={ph.caption} loading="lazy"/></a><figcaption>{ph.caption} <button aria-label="Report photo" onClick={()=>setModal({kind:'report',id:ph.id,target:'photo'})}><Flag size={12}/></button></figcaption></figure>)}</div>}
    <div className="detail-layout"><div>{p.description&&<section className="detail-section"><h2>About this place</h2><p className="place-description">{p.description}</p></section>}<section className="detail-section"><p className="eyebrow">BEFORE YOU BOOK</p><h2>Good to know</h2><div className="info-note"><ShieldCheck size={22}/><div><strong>Gluten-free menu information</strong><ul className="menu-summary">{(p.menu_options||['unknown']).map(value=><li key={value}>{value==='unknown'?'Menu options not yet confirmed':MENU_OPTIONS.find(option=>option.value===value)?.label}</li>)}</ul>{p.menu_info&&<p>{p.menu_info}</p>}<span className="small muted">Community-provided information. Confirm your requirements with the place when booking.</span></div></div>{!!p.cam_verified&&<p className="small muted">CAM status manually checked by a site admin on {p.cam_verified_at?.slice(0,10)}. This community website is independent of CAM. <a href="/about#verification">About verification</a></p>}</section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">FROM OUR COMMUNITY</p><h2>Experiences at the table</h2></div><span className="review-count">{detail.feedback.length}</span></div>{!detail.feedback.length&&<div className="empty-state compact"><MessageCircle/><h3>Be the first to share</h3><p>A few words about your visit can help the next person.</p></div>}{detail.feedback.map(f=><article className="review" key={f.id}><div className="review-heading">{f.kind==='imported'&&<div className="avatar">✳</div>}<div><AuthorIdentity author={f.kind==='imported'?null:f.author} name={f.kind==='imported'?'Imported community feedback':f.author_name}/><p className="small muted">{f.kind==='imported'?'From the original community directory':f.visit_date?`Visited ${f.visit_date}`:'Community review'}</p></div>{f.rating!==null&&<Rating rating={f.rating}/>}</div><p className="review-body">{f.body}</p><div className="review-actions">{owner&&<button onClick={()=>setModal({kind:'reply',id:f.id})}><MessageCircle size={14}/> Reply as owner</button>}<button onClick={()=>setModal({kind:'report',id:f.id,target:'feedback'})}><Flag size={13}/> Report</button></div>{detail.replies.filter(r=>r.feedback_id===f.id).map(r=><div className="owner-reply" key={r.id}><div className="reply-identity"><AuthorIdentity author={r.author} name={r.author_name}/><span className="badge">Owner reply</span></div><p>{r.body}</p><button className="text-link small" onClick={()=>setModal({kind:'report',id:r.id,target:'reply'})}>Report reply</button></div>)}</article>)}</section><Sponsor ad={adverts.find(a=>a.placement==='detail')}/></div>
    <aside className="place-sidebar">{!!detail.branches?.length&&<section className="sidebar-card"><h3>Other locations</h3><p className="small">Reviews and verification apply to each branch separately.</p>{detail.branches.map(branch=><a className="sidebar-link" key={branch.id} href={`/places/${branch.slug}`}>{branch.branch_name||branch.locality||branch.name} <ArrowUpRight size={16}/></a>)}</section>}<section className="sidebar-card"><h3>Visit or order</h3>{p.premises==='none'&&<p>No public premises</p>}{!!p.services?.length&&<p>{p.services.join(' · ')}</p>}{p.advance_orders==='yes'&&<p>Advance orders required</p>}{p.advance_orders==='no'&&<p>Advance orders not required</p>}{p.ordering_info&&<p className="preserve-lines">{p.ordering_info}</p>}<p className="price-large">{p.price_applicability==='not_applicable'?'':p.price_min===null?'Price to be confirmed':'€'.repeat(priceBand(p.price_max??p.price_min))}</p><p>{priceLabel(p)}</p>{p.price_applicability!=='not_applicable'&&p.price_min!==null&&<p className="small muted">{p.price_basis}. Estimate updated {p.price_updated?.slice(0,10)||'date unknown'}.</p>}<hr/><p className="location"><MapPin size={17}/>{p.address||p.locality||'Address to be confirmed'}, {p.island}</p>{p.premises!=='none'&&<a className="button full" href={directions} target="_blank" rel="noreferrer">Open Google Maps <ArrowUpRight size={16}/></a>}{([['website','Website'],['menu_url','View menu'],['social_url','Social page']] as const).map(([key,label])=>p[key]&&<a className="sidebar-link" key={key} href={p[key]} target="_blank" rel="noreferrer">{label}<ArrowUpRight size={16}/></a>)}{p.phone&&<a className="sidebar-link" href={`tel:${p.phone.replace(/[^+\d]/g,'')}`}>Call the place <Phone size={16}/></a>}</section><section className="sidebar-card soft"><h3>Keep local knowledge growing</h3><p className="small">Something changed? Help keep this place up to date.</p><button className="text-link" onClick={()=>setModal({kind:'correction'})}>{owner?'Edit place details':'Suggest a correction'} <Pencil size={14}/></button></section>{!owner&&<button className="owner-claim" onClick={()=>setModal({kind:'owner_claim'})}>Is this your business? Request owner access</button>}</aside></div>
    {modal&&<Modal title={({review:'Share your experience',photo:'Share a photo',reply:'Reply as the owner',report:'Report content',correction:owner?'Edit place details':'Suggest a correction',owner_claim:'Verify your owner access'} as Record<string,string>)[modal.kind]} onClose={()=>setModal(null)}>{!member?<SignInPrompt/>:modal.kind==='review'?owner?<Notice>Owners cannot rate their own businesses. You can reply to community feedback instead.</Notice>:<ReviewForm admin={member?.role==='admin'} place={p}/>:modal.kind==='photo'?<PhotoForm admin={member?.role==='admin'} placeId={p.id}/>:modal.kind==='correction'?<PlaceForm member={member} place={p} businessTypes={businessTypes} glutenFreeItems={glutenFreeItems}/>:<MessageForm admin={member?.role==='admin'} kind={modal.kind as 'reply'|'report'|'owner_claim'} placeId={p.id} targetId={modal.id} targetType={modal.target}/>}</Modal>}
  </div>;
}
